### ISSUE TITLE
Create components for the projects page

### ISSUE THREAD

**Issue by ehrelevant** [up-csi/up-csi.github.io#102]
This issue is related to #23. A few weeks ago, we received a [revised design](https://www.figma.com/design/nG8W0j19Al9LDgdscOqCoc/CSI?node-id=117-1158&t=x0LBjviwQw5dYaGk-1) for the Projects page of the UP CSI website (courtesy of Elle). I believe that the design is polished enough that there should be no issues with us making progress on this page already. 

# Tasks

Let's get this process started by preparing some of the components that we will need for this page. These components are listed below:

- [x] Social Media Panel (#107)
  - It'll contain the same social media links as the ones on the footer, but will be displaying social media icons instead of just text.
  - Take note of our usage of [Iconify](https://iconify.design/docs/icons/) for loading icons from online.

- [x] Details/Dropdown Component (#104)
  - Consider checking #79 and #98 since they are similar.
  - For the most part, this is just styling the existing component, but feel free to improve on it if you would like to (i.e. by adding animations).

- [x] General Contact Information (#106)
  - For content, just include the email on the footer and our location (Department of Computer Science, UP Diliman, etc.).

- [x] General FAQs (#105)
  - Pretty much implement it as it is.
  - We're still getting content for this, so just use Lorem Ipsum in the meantime.

Again, **the Figma design for this page can be viewed [here](https://www.figma.com/design/nG8W0j19Al9LDgdscOqCoc/CSI?node-id=117-1158&t=x0LBjviwQw5dYaGk-1)**.

~~For more details, please check the corresponding sub-issues that I'll be attaching in a moment~~ (I can't make sub-issues apparently).

# Committee Internship & Getting Started

Since it's currently committee internship season, we'll be assigning the creation of these components to our Website Team interns. I'd imagine that some of you might not be familiar with GitHub or how to get started. So, I'll just be giving a quick tutorial on how to set things up (I'll be skipping over some things).

## Setup

To start, ensure that you have installed [`Node.js`](https://nodejs.org/en) and [`pnpm`](https://pnpm.io/) (See installation guide [here](https://pnpm.io/installation)). Now, make sure to fork this repository by clicking the **fork** button (only copy `main`) and create a new fork.
![forks](https://github.com/user-attachments/assets/ee8e307e-e5f2-4fd4-95d4-3fb59749b36d)

Now, you should be on the forked repository. From here, clone the fork onto your local machine.

```bash
# Via HTTPS
git clone https://github.com/<your-username-here>/up-csi.github.io.git

# Via SSH
git clone git@github.com:<your-username-here>/up-csi.github.io.git
```

> [!CAUTION]
> If you are working on a **Windows machine** or are using a **Windows filesystem**, you will run into an issue due to how [Git handles line-endings on different operating systems](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings). To avoid this, please ensure that you disable `autocrlf` before cloning this repository. To do so, run the following `git` command:
> ```bash
> git config --global core.autocrlf false
> ```
> For more details on why the Engineering Committee imposes this configuration, see our collective confusion on this [relevant PR (comment)](https://github.com/up-csi/up-csi.github.io/pull/84#issuecomment-2388406206)

Navigate into the directory of your clone, then install the project dependencies through `pnpm`.

```bash
# Install the project dependencies.
pnpm install
```

At this point, your local repository should now be set up and you should be able to start developing on the website! For this, you may run a developer server for easy testing. 

```bash
# Starts a developer server at `localhost:5173` by default.
# Live-reloading and hot module replacement are enabled.
pnpm dev
```

> [!NOTE]
> For additional commands, check out this repository's [README](https://github.com/ehrelevant/up-csi.github.io?tab=readme-ov-file#development).

## Submitting PRs

To get started on submitting a new change or feature, make sure you create a new branch first.

```bash
# Create and switch to a new feature branch
git switch -c <feature-branch-name-here>
```

When making commits, as much as possible, keep your commits small (but not _too_ small) and commit often. Additionally, don't forget to follow **[conventional commits](https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13)**. _Not following these, may get your PR rejected_.

Before pushing your changes to your fork's remote repository, make sure that the formatters and linters run without any complaints first (Warning: They complain a lot).

```bash
# Check the code formatting with Prettier.
pnpm fmt

# Apply Prettier's suggestions.
pnpm fmt:fix

# Run all linters: HTMLHint, Stylelint, ESLint, and Svelte Check.
pnpm lint 
```

After pushing your changes to your remote repository, you can then submit a pull request. When submitting a pull request, try to be detailed. Mention your changes, how you implemented them, known issues with your implementation, any questions you may have, or anything else that may seem relevant. Be sure to also respond to comments on your PRs as soon as you are available.

# Learning Resources & Other Details

When implementing the components, you don't need to follow the design perfectly (especially with the colors), but still try your best to follow it. If possible, also implement [responsive styling](https://tailwindcss.com/docs/responsive-design) and [dark mode](https://tailwindcss.com/docs/dark-mode) to your component.

For your reference, I suggest checking out this [tutorial on the Svelte website](https://svelte.dev/tutorial/svelte/welcome-to-svelte), the [Svelte 5 documentation](https://svelte.dev/docs) and the [TailwindCSS Documentation](https://tailwindcss.com/). Additionally, I highly suggest checking out [CSS flexboxes](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox) if you aren't already familiar with them.
