### ISSUE TITLE
Fix NavBar href for Projects page, Remove unfinished features

### ISSUE THREAD

**Issue by syncopascual** [up-csi/up-csi.github.io#52]
Assigned to @galierie!

This is just a list of miscellaneous fixes for things that are unfinished/have to be removed for logistical reasons:

- [x] Remove carousel component from the page for now (#53)
- [x] Remove newsletter page from the NavBar (#54)
- [x] Fix Projects page href for the NavBar (for both desktop and mobile versions) (#54)

**Comment by BastiDood** [comment]
Completed in #53 and #54.
